name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  actions: read
  id-token: write
  security-events: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Microsoft Security DevOps
        id: msdo
        uses: microsoft/security-devops-action@v1
      - name: Upload SARIF as build artifact
        uses: actions/upload-artifact@v4
        with:
          name: msdo-sarif-results
          path: ${{ steps.msdo.outputs.sarifFile }}
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: pip
      - run: pip install --use-deprecated=legacy-resolver -r requirements.txt
      - run: python -m compileall -q pygoat
